# Maicraft 客户端配置模板
# 将此文件复制为 config.yaml 并根据需要修改。

minecraft:
  host: 127.0.0.1        # Minecraft 服务器地址
  port: 25565            # 端口
  username: MaiBot       # 机器人用户名（离线模式）
  password:              # 在线模式密码（offline 留空）
  auth: offline          # offline | microsoft | mojang
  version: "1.19.0"      # 可选，留空自动检测

enabledEvents:
  - chat
  - playerJoin
  - playerLeave
  - playerCollect
  - mobSpawn
  - blockBreak
  - blockPlace
  - healthUpdate
  - experienceUpdate
  - weatherChange

# 不能破坏的方块列表配置
# 机器人路径查找时会避免破坏这些方块
blocksCantBreak:
  - chest        # 箱子
  - furnace      # 熔炉
  - bed          # 床
  - door         # 门
  - trapdoor     # 活板门
  - sign         # 告示牌
  - torch        # 火把
  - lantern      # 灯笼

# 截图功能配置
screenshot:
  enabled: true            # 是否启用截图功能（需要额外依赖）
  width: 1920             # 图像宽度，默认 1920
  height: 1080            # 图像高度，默认 1080
  viewDistance: 12        # 视距，默认 12
  jpgQuality: 95          # JPG质量，默认 95
  loadWaitTime: 2000      # 世界加载等待时间(ms)，默认 2000
  renderLoops: 10         # 渲染循环次数，默认 10

# 调试命令系统配置
debugCommands:
  enabled: false           # 是否启用调试命令系统
  adminPlayers:           # 管理员玩家列表，只有这些玩家才能使用调试命令
    # - "YourPlayerName"    # 替换为你的游戏用户名
  chatFeedback: true      # 是否在游戏中显示调试命令的执行结果

# 聊天过滤配置
chatFilters:
  enabled: true           # 是否启用聊天过滤功能
  # 玩家黑名单：不接收这些玩家的消息
  blockedPlayers:
    # - "SpamBot"          # 示例：屏蔽垃圾消息机器人
    # - "AnnoyingPlayer"   # 示例：屏蔽讨厌的玩家
  # 消息黑名单：不接收匹配这些正则表达式的消息
  # 注意：如果调试命令系统未启用，将自动过滤以!开头的消息
  blockedMessagePatterns:
    # - "^\\s*spam\\s*$"    # 示例：屏蔽只包含"spam"的消息（不区分大小写）
    # - "广告"               # 示例：屏蔽包含"广告"的消息
    # - "\\b(?:fuck|shit|damn)\\b"  # 示例：屏蔽脏话（单词边界匹配）

# 日志配置
logging:
  level: INFO             # DEBUG | INFO | WARN | ERROR
  enableFileLog: true     # 是否启用文件日志
  logFilePath: ""         # 日志文件路径，留空使用默认路径 (logs/maicraft-*.log)
  useStderr: true         # 是否使用 stderr 输出（MCP 模式建议保持 true）
  colors: true            # 是否启用颜色输出
  timestamp: true         # 是否显示时间戳

# MCP Server 配置
mcp:
  name: "Maicraft MCP"
  version: "0.1.0"
  tools:
    # 工具过滤配置（可选）
    # 方式1：黑名单模式（推荐）- 屏蔽指定工具，其他全部可用
    disabled:
      - use_chest
      - smelt_item
    # 方式2：白名单模式 - 仅暴露指定工具
    # enabled:
    #   - mine_block
    #   - place_block
    #   - follow_player
    # 方式3：同时使用 - 白名单允许的集合减去黑名单
    # enabled:
    #   - mine_block
    #   - place_block
    #   - chat
    # disabled:
    #   - chat
    # 方式4：不配置 - 默认暴露所有工具
    # （删除或注释掉 tools 部分）